name: alumni_connect_mobile
description: Alumni Connect mobile client.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.7.0
  go_router: ^14.6.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  stomp_dart_client: ^2.1.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
